# Generated by Django 5.0 on 2024-05-19 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_alter_task_assigned_to'),
    ]

    operations = [
    ]
